name: built_value_example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  built_value_converter:
    path: '../../type_converters/built_value_converter'
  boomerang:
    path: '../../boomerang'
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  http: ^0.12.0+4

dev_dependencies:
  build_runner: ^1.0.0
  built_value_generator: ^7.0.9
  test: ^1.0.0
  pedantic: ^1.8.0
