name: boomerang
description: An elegant, codegen-less (and mirrorless) network abstraction layer for dart.
version: 0.1.0
homepage: https://github.com/saied89/boomerang
repository: https://github.com/saied89/boomerang/tree/master/boomerang

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  uri: ^0.11.3+1
  http: ^0.12.0+4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  test_coverage: ^0.4.1

