name: example
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  serializable_converter:
    path: '..'
  json_serializable: ^3.2.0

dev_dependencies:
  build_runner: ^1.0.0
  pedantic: ^1.8.0
  test: ^1.6.0
