name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
    - name: Dowload ReRes
      run: wget https://github.com/saied89/reqres/releases/download/0.0.2/reqres-0.0.1-all.jar
    - name: Run ReqRes
      run: java -jar reqres-0.0.1-all.jar
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
